### ISSUE TITLE
[GEOFENCE] McDonald's app crashs when the user open the app

### ISSUE THREAD

**Issue by lpernelle-wgs** [Woosmap/geofencing-ios-sdk#79]
# Module/Page
iOS --> Geofence Isochrone

# Current behaviour 😓
As a McDonald's user, when I open the McDo app, then the app crashs due to the Woosmap Geofencing SDK

# Expected behaviour 😀
As a McDonald's user, when I open the McDo app, then the app works.

## Supporting information
```
Crashed: com.apple.main-thread
0  WoosmapGeofencing              0x2e510 specialized static Regions.getRegionFromId(id:) + 4361594128 (<compiler-generated>:4361594128)
1  WoosmapGeofencing              0x48140 LocationService.addRegionLogTransition(region:didEnter:fromPositionDetection:) + 4361699648 (<compiler-generated>:4361699648)
2  WoosmapGeofencing              0x4f1d8 specialized LocationService.locationManager(_:didExitRegion:) + 4361728472
3  WoosmapGeofencing              0x408c8 @objc LocationService.locationManager(_:didExitRegion:) + 4361668808
4  CoreLocation                   0x2cd9c CLClientStopVehicleHeadingUpdates + 74500
5  CoreLocation                   0xe008 CLCopyAppsUsingLocation + 1936
6  CoreLocation                   0xa2b4 CLCopyTechnologiesInUse + 21932
7  LocationSupport                0x2384 (Manquant UUID ed72e51e1e993b5e8499225fc2122063)
8  CoreFoundation                 0x6d18c __CFRUNLOOP_IS_CALLING_OUT_TO_A_BLOCK__ + 20
9  CoreFoundation                 0x6dfb0 __CFRunLoopDoBlocks + 408
10 CoreFoundation                 0xa8fc __CFRunLoopRun + 788
11 CoreFoundation                 0x1dc30 CFRunLoopRunSpecific + 572
12 GraphicsServices               0x1988 GSEventRunModal + 160
13 UIKitCore                      0x4e5c50 -[UIApplication _run] + 1080
14 UIKitCore                      0x27f3d0 UIApplicationMain + 336
15 McDonalds                      0x6e18 main + 15 (AppDelegate.swift:15)
16 ???                            0x1053f43d0 (Manquant)
```

**Comment by lpernelle-wgs** [comment]
**Minutes of the meeting with Issif (iOS developer at McDonald's France)**

There is no crash in the 6.6.1 version of the app (Woosmap 1.5.1)
There is 900 crashs for 350 users in the 6.7.0 of the app (Woosmap 1.6.4)

Geomarketing feature is not enabled, just the Click&Ready is enabled.

The crash comes from the getRegionFromId() method of the iOS SDK. This method was updated between 1.5.1 and 1.6.4.

There is a "try catch" in this method that does not appear to be working.

**Comment by sameerdhulap** [comment]
Please let me know what exact scenarios when user facing crash. if video to explain it will be best

**Comment by lpernelle-wgs** [comment]
The crash comes from this method --> [Link to `getRegionFromId()`](https://github.com/Woosmap/geofencing-ios-sdk/blob/278210faa57837065c3293f7982a50e7eda37c0d/WoosmapGeofencing/Sources/WoosmapGeofencing/Business%20Logic/Region.swift#L97)

In this method, the SDK tries to split a string and use the second element of the generated array. To reproduce the crash, you can try to call this method with a random string like `"abcd"`.

I think `do{} catch{}` is not well implemented and maybe we have to do something in the catch like `return nil` because I'm not sure the line 111 is called when there is an error in the `do{....}`

**Comment by lpernelle-wgs** [comment]
There is no scenario to reproduce the error. Even McDonald’s is not able to reproduce it. A tiny part of users encountered this issue.

**Comment by sameerdhulap** [comment]
I am able to reproduce bug with this test case

```
func getRegionFromId(id: String) -> Region? {
        do {
            var identifier = id
            if((id.contains(LocationService.RegionType.poi.rawValue) || id.contains(LocationService.RegionType.custom.rawValue))){
                identifier = id.components(separatedBy: "<id>")[1]
            }
            let realm = try Realm()
            let predicate = NSPredicate(format: "identifier == %@", identifier)
            let fetchedResults = realm.objects(Region.self).filter(predicate)
            if let aRegion = fetchedResults.last {
               return aRegion
            }
        } catch {
            print("Unexpected error: \(error).")
        }
        return nil
    }
```
and calling  with this parameter `getRegionFromId(id: "poi123")`

It break at line `identifier = id.components(separatedBy: "<id>")[1]`

Solving by changing logic like 
```
if((id.contains(LocationService.RegionType.poi.rawValue) || id.contains(LocationService.RegionType.custom.rawValue))
               && id.contains("<id>")){
                identifier = id.components(separatedBy: "<id>")[1]
            }
```
